

###
GET http://localhost:3000/api/v1/workouts
###

GET http://localhost:3000/api/v1/workouts/getWorkoutsTest

###

GET http://localhost:3000/api/v1/workouts/fillWorkouts

###


###
GET http://localhost:3000/api/v1/workouts/search/legs

###
GET http://localhost:3000/api/v1/workouts/removeWorkoutFromTable/2

###

GET http://localhost:3000/api/v1/workouts/getWorkoutById/100


###
POST http://localhost:3000/api/v1/workouts?workoutTitle="Cardio"
Content-Type: application/json

{
    "sets": 3,
    "rest": 60,
    "supersets": true,
    "squats": 3,
    "lunges": 10,
    "leg press": 10  
}




###
GET http://localhost:3000/api/v1/workouts/getUserWorkouts/tanner

###


###
GET http://localhost:3000/api/v1/workouts/removeWorkout/0

###
POST http://localhost:3000/api/v1/workouts/addWorkout
Content-Type: application/json

{
    "username": "tanner",
    "workoutType": "test",
    "description": "test",
    "intensity": "Normal"
}

###
POST http://localhost:3000/api/v1/workouts/editWorkoutById
Content-Type: application/json

{
    "description": "hey stones",
    "intensity": "High",
    "id": 1
}

###
GET http://localhost:3000/api/v1/workouts/getFriendsActivities